# Generated by Django 4.1.7 on 2023-03-20 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_out', models.DateTimeField(default=None)),
                ('country', models.CharField(max_length=100)),
                ('director_film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dir', to='kino.director')),
                ('genre_film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gen', to='kino.genre')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
            },
        ),
        migrations.CreateModel(
            name='Afisha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateTimeField(auto_now_add=True)),
                ('films_af', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='af', to='kino.films')),
            ],
            options={
                'verbose_name': 'Afisha',
                'verbose_name_plural': 'Afishes',
            },
        ),
    ]
