# Generated by Django 4.1.7 on 2023-03-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afisha',
            old_name='films_af',
            new_name='films_existed',
        ),
        migrations.AlterField(
            model_name='afisha',
            name='dates',
            field=models.DateTimeField(default=None),
        ),
    ]
