# Generated by Django 4.1.7 on 2023-03-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0002_rename_films_af_afisha_films_existed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afisha',
            options={'verbose_name': 'Афиша', 'verbose_name_plural': 'Афиши'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Режиссер', 'verbose_name_plural': 'Режиссеры'},
        ),
        migrations.AlterModelOptions(
            name='films',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
    ]
